context:
  version: "2.1.6"

package:
  name: mactop
  version: ${{ version }}

source:
  url: https://github.com/metaspartan/mactop/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 5dd47033c00a56859674c149a90118ce39c7a0c5e1e30cefa714b71f943dbf47
  target_directory: src

build:
  skip: not (osx and arm64)
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/mactop -ldflags="-s -w"

requirements:
  build:
    - ${{ stdlib("c") }}
    - ${{ compiler("c") }}
    - ${{ compiler("go-cgo") }}
    - go-licenses

tests:
  - script: mactop -h
  - package_contents:
      bin:
        - mactop
      strict: true

about:
  homepage: https://github.com/metaspartan/mactop
  summary: Apple Silicon Monitor Top
  description: |
    mactop is a simple terminal based Apple Silicon power monitor written in Go.
    It displays CPU, memory, disk, network, battery, temperature, and fan information
    on macOS systems with Apple Silicon.
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/metaspartan/mactop

extra:
  recipe-maintainers:
    - xhochy
