context:
  version: "2.1.5"

package:
  name: mactop
  version: ${{ version }}

source:
  url: https://github.com/metaspartan/mactop/archive/refs/tags/v${{ version }}.tar.gz
  sha256: df49979c413b8a3a6e98ccfb553fafeb94fd652ec13a830205d057c8d73cace7
  target_directory: src

build:
  skip: not (osx and arm64)
  number: 0
  script:
    - cd src
    - go-licenses save . --save_path ../library_licenses
    - go build -v -o $PREFIX/bin/mactop -ldflags="-s -w"

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ compiler("go-cgo") }}
    - go-licenses

tests:
  - script: mactop -h
  - package_contents:
      bin:
        - mactop
      strict: true

about:
  homepage: https://github.com/metaspartan/mactop
  summary: Apple Silicon Monitor Top
  description: |
    mactop is a simple terminal based Apple Silicon power monitor written in Go.
    It displays CPU, memory, disk, network, battery, temperature, and fan information
    on macOS systems with Apple Silicon.
  license: MIT
  license_file:
    - src/LICENSE
    - library_licenses/
  repository: https://github.com/metaspartan/mactop

extra:
  recipe-maintainers:
    - xhochy
